import { scoreCandidate } from "../assetScorer.js";
import { selectFalModel, selectFalProvider } from "../sourcePolicy.js";
import type { AssetCandidate, AssetIntent, SourceProvider } from "../types.js";

export function falCandidates(input: {
  prompt: string;
  intent: AssetIntent;
  priority: SourceProvider[];
  style?: string;
  imageInput?: boolean;
  limit: number;
}): AssetCandidate[] {
  const provider = selectFalProvider(input.intent);
  const model = selectFalModel(input.intent, Boolean(input.imageInput));
  const title = `${input.prompt} generated by ${model}`;
  const candidate: AssetCandidate = {
    id: `${provider}:${model}:${slug(input.prompt)}`,
    provider,
    intent: input.intent,
    title,
    description: "fal 3D generation candidate. Requires CREATIVE_MCP_ENABLE_FAL_3D=true and server-side FAL_KEY to submit.",
    format: "glb",
    license: "Generated",
    generated: true,
    score: scoreCandidate({
      provider,
      providerPriority: input.priority,
      intent: input.intent,
      prompt: input.prompt,
      title,
      format: "glb",
      license: "Generated",
      style: input.style,
      generated: true
    })
  };
  return [candidate].slice(0, input.limit);
}

export async function submitFalGeneration(input: {
  model: string;
  prompt: string;
  imageUrls?: string[];
  enablePbr?: boolean;
  faceCount?: number;
  webhookUrl?: string;
}): Promise<{ submitted: boolean; reason?: string; response?: unknown }> {
  if (process.env.CREATIVE_MCP_ENABLE_FAL_3D !== "true") {
    return { submitted: false, reason: "CREATIVE_MCP_ENABLE_FAL_3D is not true" };
  }
  if (!process.env.FAL_KEY) {
    return { submitted: false, reason: "FAL_KEY is not set server-side" };
  }
  const imported = await import("@fal-ai/client") as unknown as { fal: any };
  imported.fal.config({ credentials: process.env.FAL_KEY });
  const requestInput: Record<string, unknown> = {
    prompt: input.prompt,
    enable_pbr: input.enablePbr ?? true
  };
  if (input.faceCount) requestInput.face_count = input.faceCount;
  if (input.imageUrls?.length) {
    requestInput.image_url = input.imageUrls[0];
    requestInput.image_urls = input.imageUrls;
  }
  const response = await imported.fal.queue.submit(input.model, {
    input: requestInput,
    webhookUrl: input.webhookUrl
  });
  return { submitted: true, response };
}

export function smartTopologyModel(): string {
  return "fal-ai/hunyuan-3d/v3.1/smart-topology";
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "").slice(0, 80) || "asset";
}
